# Generated by Django 4.0.4 on 2022-09-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='my_books',
        ),
    ]
